
# Travis CI configuration for Slack Topic Updater.
#
# @see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# @see https://docs.travis-ci.com/user/database-setup/#postgresql
# @author Tim Malone <tdmalone@gmail.com>

language: node_js
node_js: 10.11.0

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn --frozen-lockfile

script:
  - yarn lint
  - yarn test

after_script:
  - yarn report-coverage

# Deploy tagged commits to npm.
deploy:
  provider: npm
  email: tdmalone@gmail.com
  api_key:
    secure: BnelfzHTlzGzFJ5FOkzpRxY4+Ld76RmoYGFN5SSrTekWSQeS0J0KD/vIGFteVGoALIM7hLJw0tcU6KKcCMJXoJapwSOZBHsBJOZIRAyTk6ahBejs4cSoF/xf/54dRkJH0+ZTtOKIEajgpigTqx4iai35qoDrj/G81OnVTmMMKpS50BLy2GCWm/AZsi3QRvA5s8c4vUT/mSAZFK/fi2adgj6mkd7YKrswYhfvVRRmColZ8RiRgWCd3yDp+D6Lwrz1W4BrVe3rb+KrCehaMsU6m5wJTi8gGgncrlp6y5PtNysE7eqLov5+b8oGG4MkjSO327aNxANzk3xyvtaa0a5hZa9wjzNE0NH41nE+xaxFCv0+YYJzKgpt4QyPnwO7YHNrnJjJ1W2uFSsBwRMuo3cGUez5gaGtfZfikOvkqruwRaJDkuASuMbCr+05LeX/NGF0FlUVzjs70ZjyvucRhcu3aKVP/nJRGEqs4Tx9pwlc4yocZwjW38w0szwFzjPizwy+Vl9zHm/dsR7n0sEFFEJv/LKgnMUTwhYd+YKFBkBZA4qkXuzUmlf1lCCRfpXLnqZRRjI60Ge8svyfsfo+Lk64obD3+WL8IwM/j8Uy/6SWxXsH21xRm5DEyeK+M0E0dA0XDvE0eBu8kQs6FWP4Z08QpI8H4QNxCL1pIZ1DBGGyviQ=
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      - secure: CnAWkxkmaVh8uCfYrBiD7KUieUTuf8CxK8b5wq0WF/0e2TprsE1RtDeuOqiuKcI45hy96R16CQ3pnT2ckqIOWsTNEpJQTPex8xe5rbHjxewDc0hzRD4m/r8UIQcl2kBBDlrNRZDz9hOnG+PefH5zhOAwt9+8ioVm62ALoWrjE1VHBVQQG9lXKhei/kVNLxVVqnO2ncv08Rorwev/ds25VHldIxMLSmV4XaLms7WcMfN9dHcSPR8rQLbrGMe7tKNtQJgn/1gOFR/s2vXBvismj06avLZ/0XOPpQgxYwj0v3JJSm7iSIgTJeUq2FZAvMGdalXUGdnd2DB9KM1ud6AfJv9TmVn1VoQWBH6jiNh4NH1V12vUg96xGkhwdTLZnDq8FUZ1DCi/DP0onR10z7fkhsiCkOLXScuxDAuXVucLvDRRGNzXnzHPm/q7eFOarTix01xXxdkDzNfZCpaVkiTcF/GTIvraZI2NR9izVVzc2A/LOIxj3EGVvupPvQbWQPSS1yfnPx45u9M88oyh0DERkosCMMj2bx8mIMXUAc9E9S75gb8KpEhYQjEyqZY3XJ6WugjqVDIfa5Pc2PAihXRPgFnaYKp3tdBKiSUcsBExpCnIxklXeXND2AS2umqI4DD9MhX7Vx+7iggo2x2/xmTuZdd5WQofzuU6M67Zi4ZrGvM=
    on_start: always
