
# Travis CI configuration for Slack Topic Updater.
#
# @see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# @see https://docs.travis-ci.com/user/database-setup/#postgresql
# @author Tim Malone <tdmalone@gmail.com>

language: node_js
node_js: 10.11.0

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn --frozen-lockfile

script:
  - yarn lint
  - yarn test

after_script:
  - yarn report-coverage

# Deploy tagged commits to npm.
deploy:
  provider: npm
  email: tdmalone@gmail.com
  api_key:
    secure: gmrRKaZ1cjC5uBNYmcoYv910/pxzl11iG6fR8CLYf0Etob5F/RnvoEaQzmSyAAZdv/86J4lBMcQ0g20AeE7+TkUT7g/5ztpmE0a609Fq2K2zRa9kzZ1HK0CBwya6rDv2+wsdB37fB8C4m6K15Om2fstoy7P765ja6NBCnCoHSvhduwunrr/AK+RKmG+8lSxQitZatPn2rF0RmZhcJnrO09xNms0mD/TtmhZ6NMhbI5pqdq7AdSlXVM2sCqKnBgvFibVmaDWs2oZTnm6Puko83yLbo8JwSaPqlIsHQcvv7W0iBkwgBly99GThT+P/yLMyxG/L1+IwpG3pJwM7YFL156fSi38+8mpssy55OU+7DeP+NwzeEhcI9eicb4M5NLL0w0qS6bLiyWWfByQmcQff1ybEtuMGVSLjvH2GbXFeFWEWj9dpaTxVlT1ywUJRx+Vgzi6AM9HDg3J++pJ9l+QBanXxyJJt9F3c01qHfg8AdK1S/LnYSdjpOfc17MAxw0xkLhX76r9ZT6e82UaI5W5KG3RvnB3zHy3g8du/+7ncbxFSTYTjZVGRHE8FetcMt6eTTF1JtMKGR9H2F1BciB/DmdBa02CrxhUW4w/eFzz1c+fkwVlEXiFixfrdMlWX0aLUCS9z0iTeyJhfGPGFtTni1it/J9NoJlN/mTaco5zK3O8=
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      - secure: c1EiAokrLyd79lkSG6OvzIhOqLKBF2kiyjAFhiYfSp1EsCkqHTQ0TgH5e61Jix+VoJL/u6ydkb0YH5BHpuTYv27sxXRAjaGn9I4jhpo13DMX6ZXqpLgZAcONLQ5KqEBvyLPr3eixVTrE0C8BpRmGSmsMbjEqImpK0lm0jzGK6DlakAFT4M8w/oHvG5hc30/FE37UXW6R9EsOrskaflZvP4EGfWwvHJZHAtuAtaPkClSQpyOs9JUQU7/OWzYXEJKEn+SGAOedxKOq78e0u5cT8Egn0uLMMil6eZJ3Iey8wji5Xv5HQRnqAau7wEVrLpGvuK9r7t5JELwHM2xtRtTu+UcySNsTulEfHKuN7h9RK4wJZEBpaboqSfb+DzR6iRpVQSEwphkRPoPb9+0Ta+QF1RNhPdq38bDHCoAd22uauRwfzS2BQQPw2tnUsTDZqtwQgZtEczy3hQmiicF3W/Ib7nrT3Whv2Yo7P1ZK2PkAhSrBAakg7BME5kBURg4QdADmCMaTGIdTG7YJt1AHFAxsddIewzlROkFV7KRrkUYy6kgnvDn/qYHhzrGgOxDpRF5PvC5LvvpC3Zzl/KvYFIlF7swacpIyHqBFQ8V9OTbJSH2tqLJqpZA4To6HNEVn0dFg5gbY0pyceicKfkBL1ESkw/aA+zErxA/1GExbgrGuicU=
    on_start: always
